import STATUS_CODES from "http-response-status-code";

export const GET_METHOD = "GET";
export const POST_METHOD = "POST";
export const KNOWN_METHODS = ["DELETE", GET_METHOD, "HEAD", "OPTIONS", POST_METHOD, "PUT"];
export const TEST_METHOD_NOT_IN_SPEC = "TEST_METHOD_NOT_IN_SPEC";
export const MOST_COMMON_HTTP_STATUS_CODES = [
  STATUS_CODES.OK,
  STATUS_CODES.CREATED,
  STATUS_CODES.MOVED_PERMANENTLY,
  STATUS_CODES.MOVED_TEMPORARILY,
  STATUS_CODES.NOT_MODIFIED,
  STATUS_CODES.BAD_REQUEST,
  STATUS_CODES.UNAUTHORIZED,
  STATUS_CODES.FORBIDDEN,
  STATUS_CODES.NOT_FOUND,
  STATUS_CODES.GONE,
  STATUS_CODES.TOO_MANY_REQUESTS,
  STATUS_CODES.REQUEST_HEADER_FIELDS_TOO_LARGE,
  STATUS_CODES.INTERNAL_SERVER_ERROR,
  STATUS_CODES.BAD_GATEWAY,
  STATUS_CODES.SERVICE_UNAVAILABLE,
  STATUS_CODES.GATEWAY_TIMEOUT,
  STATUS_CODES.UNPROCESSABLE_ENTITY,
];
// We can't use any of the 1XX status codes or the server will hang
export const ALL_STATUS_CODES = Object.values(STATUS_CODES).filter((l) => Number(l) >= 200);
